In [1]:
import numpy as np
from sklearn import preprocessing

In [8]:
X = np.array([[ 1., -1.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])  ## 3 training data points and 3 features

In [3]:
X_scaled = preprocessing.scale(X) ## centers it around the mean and makes variance 1
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [4]:
X_scaled.mean(axis = 0)

array([0., 0., 0.])

In [5]:
X_scaled.std(axis= 0)

array([1., 1., 1.])

In [6]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)

scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [14]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])